spring.application.name=smartmall-ai-service

server.port=8084

smartmall.ai.base-url=https://ps.air-outer.com/v1
smartmall.ai.api-key=${AGENTROUTER_API_KEY}
smartmall.ai.model=deepseek-v4-flash
smartmall.ai.user-agent=Codex D
smartmall.ai.product-service-url=http://localhost:8081
smartmall.ai.order-service-url=http://localhost:8082

smartmall.jwt.public-key=file:G:/work/java/project/smartmall-keys/public.pem
